### ISSUE TITLE
Problem cleaning parsed names like "O'Keefe"

### ISSUE THREAD

**Issue by LocoDelAssembly** [bionomia/dwc_agent#14]
When doing `DwcAgent.clean(DwcAgent.parse("O'Keefe").first)` the cleaned name not only doesn't get moved to `family` but also it is converted into `given="O.'Keefe"`

For family names like those this line seems to be causing the problem (not to mean it can just be removed or relocated):
https://github.com/bionomia/dwc_agent/blob/6bc1194d80036e03ee4855acbff0843ddb6cfbb8/lib/dwc_agent/cleaner.rb#L82

Ref: https://github.com/SpeciesFileGroup/taxonworks/issues/2747 by @LordFlashmeow

**Comment by dshorthouse** [comment]
Thanks @LocoDelAssembly & apologies for the delay. I didn't have notifications enabled! This shouldn't be too hard to fix and I'll have a look ASAP.

**Comment by dshorthouse** [comment]
Fixed in v 3.0.0.8
