### ISSUE TITLE
Treat a string with many commas separating single words as all family names

### ISSUE THREAD

**Issue by dshorthouse** [bionomia/dwc_agent#7]
`Chaboo, Bennett, Shin`

Those are all family names but the parser says:

`[#<Name family="Chaboo" given="Bennett">, #<Name given="Shin">] `

**Comment by dshorthouse** [comment]
From @mjy on Twitter

> 2.5.1 :016 > a = 'M.R. and J.D. Smith'
 => "M.R. and J.D. Smith" 
> 2.5.1 :017 > b = a.gsub( /([A-Z]\.[A-Z]\.) (and) ([A-Z]\.[A-Z]\.) (.*)/ , "#{$1} #{$4} and #{$3} #{$4}")
 => "M.R. Smith and J.D. Smith"

**Comment by dshorthouse** [comment]
Another possibility:
`a.gsub(/^(\S{1,}\.?){1,}\s*(?i:and|&)\s*(\S{1,}\.?){1,}\s*(.*)$/, '\1 \3|\2 \3')`

**Comment by LocoDelAssembly** [comment]
Seems fixed in the sense that it identify three people, but it is assuming they're all given names rather than family names.
```rubv
2.7.2 :001 > DwcAgent.parse "Chaboo, Bennett, Shin"
 => [#<Name given="Chaboo">, #<Name given="Bennett">, #<Name given="Shin">] 
2.7.2 :002 > DwcAgent.parse "Hardy, Andrews & Giuliani"
 => [#<Name given="Hardy">, #<Name given="Andrews">, #<Name given="Giuliani">] 
2.7.2 :003 > DwcAgent::Version.version
 => "1.5.1.6" 
2.7.2 :004 > 
```

**Comment by dshorthouse** [comment]
Thanks for having a look at this. Indeed, what's expected here is that each parsed name then needs to be cleaned:
```
names = DwcAgent.parse "Chaboo, Bennett, Shin"
DwcAgent.clean names[0]
=> {:title=>nil, :appellation=>nil, :given=>nil, :particle=>nil, :family=>"Chaboo", :suffix=>nil}
```

**Comment by LocoDelAssembly** [comment]
Many thanks for pointing out `DwcAgent.clean`! Was not aware of it. Should it be included in `README.md`?

**Comment by dshorthouse** [comment]
Good point. I'll add that.
