### ISSUE TITLE
Do better handling of names like Frère León

### ISSUE THREAD

**Issue by dshorthouse** [bionomia/dwc_agent#9]
The parser strips out Frère before it has a chance to be recognized as a title. This should be retained where as John Smith, frère would need to be stripped out cc @kcopas.

**Comment by kcopas** [comment]
That happened while I was attributing some specimens—it was weird. He'd hung around as Frère León for a reasonable amount of time before that.

**Comment by dshorthouse** [comment]
There was a time when I did not parse the canonical name from wikidata prior to entry into Bloodhound, but reverted that decision some time back, likely to accommodate things like particles. The decision broke handling of titles like Frère. Working on it now. Good news is once repaired, I won't have to reharvest all of GBIF as it's (mostly) a display issue.
